language: "ko"        # 2글자 코드
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: true   # 리뷰에 코드에 Comment를 달도록 함
  high_level_summary: true         # PR에 대해 요약(요지문)
  poem: false
  review_status: false             # 상태 메시지 비활성화
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

  path_instructions:
    - path: "src/main/java/**/*.java"
      instructions: "SOLID 원칙, 스프링 어노테이션, 의존성 주입 패턴, 예외 처리에 중점을 둔다"
    - path: "src/test/**/*.java"
      instructions: "테스트 커버리지, 스프링 테스트 어노테이션, mock 사용법, 네이밍 규칙을 확인한다"
    - path: "**/*.{yml,yaml,properties}"
      instructions: "스프링 설정, 보안 설정, DB 연결, 환경 설정을 검증한다"

  path_filters:
    - "!**/build/**"
    - "!**/.gradle/**"
    - "!**/gradle/wrapper/**"
    - "!**/gradlew*"
    - "!**/out/**"
    - "!**/*.class"
    - "!**/*.jar"
    - "!**/*.war"
    - "!**/node_modules/**"

chat:
  auto_reply: true

tone_instructions: "스프링 모범 사례, SOLID 원칙, 성능 최적화, 보안 관련 사항, 적절한 JPA 사용법, 자바 코딩 표준을 강조한다"

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto