spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/webflux
    username: root
    password: letmein
    pool:
      enabled: true # 커넥션 풀 활성화

  sql:
    init:
      mode: always

  flyway:
    url: jdbc:mysql://localhost:3306/webflux
    locations: classpath:db/migration
    enabled: true
    user: root
    password: letmein
    baseline-on-migrate: true
    clean-disabled: false # flyway.cleanDisabled 속성 비활성화


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true

gemini:
  api:
    url: [Gemini API 요청 URL]
    key: [Gemini API Key]

jwt:
  secret-key: dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1hbmQtd2ViZmx1eA==
  expiration-time: 3600000